# Generated by Django 6.0.4 on 2026-04-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('success', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
